openapi: 3.0.1
info:
  title: 工作媒合平台
  version: 1.0.0
servers:
- url: https://yxpk4.com/
tags:
  - name: 會員
  - name: 公司
  - name: 履歷
  - name: 工作
  - name: 招募
  - name: 任務
  - name: 申訴
  - name: 訊息
paths:
  #user
  /v1/user/login:
    post:
      tags:
        - 會員
      summary: 會員登入
      description: 會員登入輸入帳號密碼取得token
      operationId: userLogin
      requestBody:
        description: 登入資訊
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          token:
                            type: string
                        required:
                          - token
        401:
          description: 登入失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: login failed
                  res:
                    type: object
                    nullable: true
                    example: null
                required:
                  - msg
                  - res
  /v1/user/create:
    post:
      tags:
        - 會員
      summary: 新增會員
      operationId: addUser
      requestBody:
        description: 會員資訊
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/User'
                - type: object
                  properties:
                    password:
                      type: string
                      format: password
                      description: 登入密碼
                  required:
                    - password
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        allOf:
                          - $ref: '#/components/schemas/User'
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 會員編號
        422:
          description: 欄位錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequest'     
  /v1/user/info:
    get:
      tags:
        - 會員
      summary: 取得自身會員資訊
      operationId: getUserInfo
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 會員編號
                          - $ref: '#/components/schemas/FullUser'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/info/{user_id}:
    get:
      tags:
        - 會員
      summary: 透過會員id取得會員資訊
      operationId: getUserInfoById
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 會員編號
                          - $ref: '#/components/schemas/FullUser'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/update:
    post:
      tags:
        - 會員
      summary: 更新會員資訊
      operationId: updateUser
      requestBody:
        description: 會員資訊
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        allOf:
                          - $ref: '#/components/schemas/FullUser'
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 會員編號
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/{user_id}:
    delete:
      tags:
        - 會員
      summary: 刪除會員
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: boolean
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/search/users:
    get:
      tags:
        - 會員
      summary: 取得所有會員資訊
      operationId: getAllUserInfo
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              allOf:
                                - type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: 會員編號
                                - $ref: '#/components/schemas/FullUser'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []

  #resumes
  /v1/user/resumes:
    get:
      tags:
        - 履歷
      summary: 取得自己的所有履歷列表
      operationId: getUserResumes
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  description: 履歷名稱
                                id:
                                  type: integer
                                  description: 履歷id
                              required:
                                - name
                                - id
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/resumes/{user_id}:
    get:
      tags:
        - 履歷
      summary: 取得會員所有履歷列表
      operationId: getUserResumesById
      parameters:
        - $ref: "#/components/parameters/userIdParam"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  description: 履歷名稱
                                id:
                                  type: integer
                                  description: 履歷id
                              required:
                                - name
                                - id
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/resume/{resume_id}:
    get:
      tags:
        - 履歷
      summary: 取得履歷內容資訊
      operationId: getUserResumeById
      parameters:
        - $ref: '#/components/parameters/resumeIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              user_id:
                                type: integer
                                description: 會員編號
                          - $ref: '#/components/schemas/UserResume'
                          - $ref: '#/components/schemas/ModelTimestamp'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        403:
          $ref: '#/components/responses/PermissionDenied'
      security:
        - api_key: []
    delete:
      tags:
        - 履歷
      summary: 刪除履歷
      operationId: deleteResume
      parameters:
        - $ref: '#/components/parameters/resumeIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: boolean
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        403:
          $ref: '#/components/responses/PermissionDenied'
      security:
        - api_key: []
  /v1/user/resume/create:
    post:
      tags:
        - 履歷
      summary: 新增會員履歷資料
      operationId: createUserResume
      requestBody:
        description: 會員詳細資料
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResume'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 履歷編號
                              user_id:
                                type: integer
                                description: 會員編號
                            required:
                              - id
                              - user_id
                          - $ref: '#/components/schemas/UserResume'
                          - $ref: '#/components/schemas/ModelTimestamp'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/user/resume/{resume_id}/update:
    post:
      tags:
        - 履歷
      summary: 更新會員履歷資料
      operationId: updateUserResume
      parameters:
        - $ref: '#/components/parameters/resumeIdParam'
      requestBody:
        description: 會員詳細資料
        content:
          application/json:
            schema:  
              $ref: '#/components/schemas/UserResume'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              user_id:
                                type: integer
                                description: 會員編號
                          - $ref: '#/components/schemas/UserResume'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        403:
          $ref: '#/components/responses/PermissionDenied'
      security:
        - api_key: []

  #company
  /v1/company/info:
    get:
      tags:
        - 公司
      summary: 取得自身公司資訊
      operationId: getUserCompanyInfo
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 公司編號
                            required:
                              - id
                              - avatar
                              - fax
                              - website
                              - contact_time
                              - others
                              - description
                              - remark
                          - $ref: '#/components/schemas/Company'
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/company/update:
    post:
      tags:
        - 公司
      summary: 更新公司資訊
      operationId: updateCompany
      requestBody:
        description: 公司資訊
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 公司編號
                            required:
                              - id
                              - avatar
                              - fax
                              - website
                              - contact_time
                              - others
                              - description
                              - remark
                          - $ref: '#/components/schemas/Company'
                          
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []

  #job
  /v1/jobs:
    get:
      tags:
        - 工作
      summary: 取得自己的所有工作資料
      operationId: getOwnJobslist
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              allOf:
                                - type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: 工作案件編號
                                  required:
                                    - id
                                - $ref: "#/components/schemas/Job"
                        required:
                          - data
      security:
        - api_key: []
  /v1/jobs/{user_id}:
    get:
      tags:
        - 工作
      summary: 取得會員所有工作資料
      operationId: getJobslistByUserId
      parameters:
        - $ref: "#/components/parameters/userIdParam"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              allOf:
                                - type: object
                                  properties:
                                    id:
                                      type: integer
                                      description: 工作案件編號
                                  required:
                                    - id
                                - $ref: "#/components/schemas/Job"
                        required:
                          - data
      security:
        - api_key: []
  /v1/job/info/{job_id}:
    get:
      tags:
        - 工作
      summary: 取得案件資訊
      operationId: getJobInfo
      parameters:
        - $ref: '#/components/parameters/jobIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 工作編號
                              user_id:
                                type: integer
                                description: 業主編號
                              corp_id:
                                type: integer
                                description: 公司編號
                                nullable: true
                            required:
                              - id
                              - user_id
                              - corp_id
                          - $ref: '#/components/schemas/Job'
                          - type: object
                            properties:
                              detail:
                                $ref: '#/components/schemas/JobDetail'
                            required:
                              - detail
      security:
        - api_key: []
  /v1/job/create:
    post:
      tags:
        - 工作
      summary: 新增工作
      operationId: addJob
      requestBody:
        description: 工作資訊
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Job'
                - type: object
                  properties:
                    detail:
                      $ref: '#/components/schemas/JobDetail'
                  required:
                    - detail
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        allOf:
                          - $ref: '#/components/schemas/Job'
                          - $ref: '#/components/schemas/ModelTimestamp'
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 工作編號
                            required:
                              - id
                          - type: object
                            properties:
                              detail:
                                $ref: '#/components/schemas/JobDetail'
      security:
        - api_key: []
  /v1/job/recommend:
    get:
      tags:
        - 工作
      summary: 推薦工作案件
      operationId: getJobRecommend
      parameters:
        - name: user_id
          in: query
          description: 會員id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: integer
                                description: 工作編號
                            required:
                              - id
                          - $ref: '#/components/schemas/Job'
      security:
        - api_key: []
  
  #recruitment
  /v1/job/recruit:
    post:
      tags:
        - 招募
      summary: 招募求職者（徵才）
      description: 由業主主動對網站求職者發起招募
      operationId: recruitUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecruitmentReqBody'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/job/apply:
    post:
      tags:
        - 招募
      summary: 求職者主動尋求招募機會（應徵）
      description: 由求職者向業主提出工作意願
      operationId: userApply
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecruitmentReqBody'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/recruitment/reject/{recruitment_id}:
    get:
      tags:
        - 招募
      summary: 拒絕招募
      description: 業主方或求職者方拒絕招募請求
      operationId: rejectRecruitment
      parameters:
        - $ref: '#/components/parameters/recruitmentParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/recruitment/read/{recruitment_id}:
    get:
      tags:
        - 招募
      summary: 讀取招募訊息
      description: 業主方或求職者方讀取招募請求
      operationId: readRecruitment
      parameters:
        - $ref: '#/components/parameters/recruitmentParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/recruitment/list:
    get:
      tags:
        - 招募
      summary: 業主查看相關招募清單
      description: 業主查看現有所有招募清單
      operationId: recruitmentList
      parameters:
        - name: owner_id
          in: query
          description: 業主id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: array
                        items:
                          $ref: '#/components/schemas/Recruitment'
      security:
        - api_key: []
  /v1/recruitment/invitation:
    get:
      tags:
        - 招募
      summary: 求職者查看徵才清單
      description: 求職方查看招募方主動發起的招募邀請列表
      operationId: recruitmentInvitation
      parameters:
        - $ref: '#/components/parameters/userIdQryParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: array
                        items:
                          $ref: '#/components/schemas/Recruitment'
      security:
        - api_key: []
  /v1/recruitment/application:
    get:
      tags:
        - 招募
      summary: 求職者查看應徵清單
      description: 求職方查看自己發起的招募應徵列表
      operationId: recruitmentApplication
      parameters:
        - $ref: '#/components/parameters/userIdQryParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: array
                        items:
                          $ref: '#/components/schemas/Recruitment'
      security:
        - api_key: []
  /v1/recruitment/interview:
    post:
      tags:
        - 招募
      summary: 發請面試邀請
      description: 由業主向求職者發請面試邀請
      operationId: createInterview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterviewReqBody'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []

  #task
  /v1/task/create:
    post:
      tags:
        - 任務
      summary: 排定工作任務
      description: 排定工作任務
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                job_id:
                  type: integer
                user_id:
                  type: integer
                wage:
                  type: integer
                start_date:
                  type: string
                end_date:
                  type: string
                memo:
                  type: string
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/update:
    post:
      tags:
        - 任務
      summary: 更新工作任務內容
      description: 更新工作任務內容
      operationId: updateTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                job_id:
                  type: integer
                user_id:
                  type: integer
                wage:
                  type: integer
                start_date:
                  type: string
                end_date:
                  type: string
                memo:
                  type: string
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/user/{user_id}:
    get:
      tags:
        - 任務
      summary: 勞工查看任務列表
      description: 勞工查看任務列表
      operationId: getUserTask
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/owner/{user_id}:
    get:
      tags:
        - 任務
      summary: 業主查看任務列表
      description: 業主查看任務列表
      operationId: getOwnerTask
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/{task_id}/status/{status}:
    get:
      tags:
        - 任務
      summary: 更新任務狀態
      description: |
        更新任務狀態，狀態列表如下

        (0: 尚未執行、1: 執行中、2: 執行結束、3: 已結算)
      operationId: updateTaskStatus
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/rate:
    post:
      tags:
        - 任務
      summary: 勞工評分任務
      description: 勞工對指定任務評分，分數範圍為1至5
      operationId: rateTask
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/comment:
    post:
      tags:
        - 任務
      summary: 勞工評論任務
      description: 勞工對指定任務發表評論
      operationId: commentTask
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/owner/rate:
    post:
      tags:
        - 任務
      summary: 業主評分任務
      description: 業主對指定任務評分，分數範圍為1至5
      operationId: ownerRateTask
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []
  /v1/task/owner/comment:
    post:
      tags:
        - 任務
      summary: 業主評論任務
      description: 業主對完成指定任務之勞工發表評論
      operationId: ownerCommentTask
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []

  #complaint
  /v1/complaint/create:
    post:
      tags:
        - 申訴
      summary: 新增申訴事件
      operationId: createComplaint
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                task_id:
                  type: integer
                content:
                  type: string
                img:
                  type: string
                  format: binary
                video:
                  type: string
                  format: binary
                audio:
                  type: string
                  format: binary
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - api_key: []

  #message
  /v1/chat/message/rooms:
    get:
      tags:
        - 訊息
      summary: 取得訊息聊天室列表
      operationId: getChatRoomList
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        nullable: false
                        properties:
                          data:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  description: 聊天室id
                                user_id:
                                  type: integer
                                  description: 對方user id
                                updated_at:
                                  type: string
                                  description: 最後更新時間
                              required:
                                - id
                                - user_id
                                - updated_at
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
      security:
        - api_key: []
  /v1/chat/message/room/{user_id}:
    get:
      tags:
        - 訊息
      summary: 取得訊息room id
      operationId: getChatRoomId
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        nullable: false
                        properties:
                          data:
                            type: integer
                            description: 訊息room id
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        404:
          description: 無相關會員訊息room id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                msg: chat room not found
                res: null
      security:
        - api_key: []
  /v1/chat/messages/{room_id}:
    get:
      tags:
        - 訊息
      summary: 取得訊息紀錄
      operationId: getMessageRecordsByRoomId
      parameters:
        - $ref: '#/components/parameters/roomIdParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            type: array
                            items:
                              allOf:
                                - $ref: '#/components/schemas/ChatMessage'
                                - $ref: '#/components/schemas/ModelTimestamp'
                                
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        404:
          description: 找不到會員訊息room id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                msg: chat room not found
                res: null
      security:
        - api_key: []
  /v1/chat/message/{user_id}:
    post:
      tags:
        - 訊息
      summary: 傳送訊息
      operationId: postChatMessage
      description: 注意，user_id parameter為接收者id
      parameters:
        - $ref: '#/components/parameters/userIdParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestChatMsg'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      res:
                        type: object
                        properties:
                          data:
                            allOf:
                              - $ref: '#/components/schemas/ChatMessage'
                              - $ref: '#/components/schemas/ModelTimestamp'
                        required:
                          - data
        401:
          $ref: '#/components/responses/TokenUnauthenticated'
        404:
          description: 找不到會員
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                msg: user not found
                res: null
      security:
        - api_key: []
  /v1/chat/broadcasting/auth:
    post:
      tags:
        - 訊息
      summary: 驗證私人頻道訂閱權限
      operationId: chatBroadcastAuth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                socket_id:
                  type: string
                channel_name:
                  type: string
              required:
                - socket_id
                - channel_name
      responses:
        200:
          description: successful operation
          content:
            application/json: {}
      security:
        - api_key: []

components:
  parameters:
    pageParam:
      name: page
      in: query
      description: 頁數(預設為1)
      schema:
        type: integer
    limitParam:
      name: limit
      in: query
      description: 單頁筆數(預設為24)
      schema:
        type: integer
    userIdParam:
      name: user_id
      in: path
      description: 會員id
      required: true
      schema:
        type: integer
    userIdQryParam:
      name: user_id
      in: query
      description: 會員id
      required: true
      schema:
        type: integer
    jobIdParam:
      name: job_id
      in: path
      description: 工作案件id
      required: true
      schema:
        type: integer
    recruitmentParam:
      name: recruitment_id
      in: path
      description: 招募物件id
      required: true
      schema:
        type: integer
    roomIdParam:
      name: room_id
      in: path
      description: 訊息room id
      required: true
      schema:
        type: integer
    resumeIdParam:
      name: resume_id
      in: path
      description: 履歷id
      required: true
      schema:
        type: integer

  responses:
    TokenUnauthenticated:
      description: token無效
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthenticatedRes'
    PermissionDenied:
      description: 無操作權限
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
          example:
            msg: permission denied
            res: null

  schemas:
    ApiResponse:
      type: object
      properties:
        msg:
          type: string
          example: success
        res:
          type: object
          nullable: true
      required:
        - msg
        - res
    UnauthenticatedRes:
      type: object
      properties:
        message:
          type: string
          example: Unauthenticated.
    User:
      type: object
      properties:
        name:
          type: string
          description: 姓名
        en_name:
          type: string
          description: 英文名
          nullable: true
        sex:
          type: integer
          description: 性別(0:女 1:男)
          enum: [0, 1]
        birthday:
          type: string
          format: date
          description: 生日
        marital_status:
          type: integer
          description: "婚姻狀態（0: 未婚 1: 已婚 2: 離婚 3: 喪偶）"
        phone:
          type: object
          description: 電話號碼
          properties:
            phone_1:
              type: string
            phone_2:
              type: string
            phone_3:
              type: string
          required:
            - phone_1
        special_id:
          type: integer
          description: 特殊身分
        email:
          type: string
          format: email
          description: 信箱
        contact_time:
          type: object
          description: 聯絡時間
          nullable: true
        education:
          $ref: '#/components/schemas/Education'
        skills:
          type: array
          description: 技能
          items:
            type: string
        mug_shot_img:
          type: string
          description: 大頭貼
        address:
          type: string
          description: 地址
        public_info:
          type: object
          description: 公開資訊
        public_contact_info:
          type: object
          description: 公開聯絡資訊
        privacy_setting:
          type: object
          properties:
            job_match:
              type: boolean
              description: 是否公開自動配動
            match_inform:
              type: boolean
              description: 是否開啟配對通知
            public_profile:
              type: boolean
              description: 是否公開會員資料
            resumes:
              type: boolean
              description: 是否公開履歷資料
            jobs:
              type: boolean
              description: 是否公開工作資料
          required:
            - job_match
            - match_inform
            - public_profile
            - resumes
            - jobs
          description: 隱私設定資訊
      required:
        - id
        - name
        - sex
        - birthday
        - marital_status
        - phone
        - special_id
        - email
        - education
        - skills
        - mug_shot_img
        - address
        - public_info
        - public_contact_info
        - privacy_setting
    FullUser:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            last_login:
              type: string
              format: date-time
              description: 最後登入時間
    UserResume:
      type: object
      properties:
        name:
          type: string
          description: 履歷名稱
        status:
          type: integer
          description: "狀態（0：關閉，1：開啟)"
        experiences:
          type: array
          items:
            $ref: '#/components/schemas/Experience'
          description: 經歷
        educations:
          type: array
          items:
            $ref: '#/components/schemas/Education'
          description: 學歷
        lang_skills:
          type: array
          description: 外語能力
          items:
            $ref: '#/components/schemas/LangSkill'
        certificates:
          type: array
          description: 證照列表
          items:
            $ref: '#/components/schemas/Certificate'
        skills:
          type: array
          description: 技能
          items:
            type: string
        attachments:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: 名稱
              path:
                type: string
                description: 路徑
          description: 附件
      required:
        - status
        - experiences
        - education
        - lang_skill
        - certificates
        - skills
    Experience:
      type: object
      properties:
        position:
          type: string
          description: 經歷職務名稱
        company:
          type: string
          description: 經歷公司名稱
        type:
          type: integer
          description: "經歷工作類別 (0: 全職, 1:兼職, 2:實習)"
        title:
          type: array
          items:
            type: string
          description:  經歷工作職稱
        management:
          type: integer
          description: "經歷管理責任 (0: 10人以下, 1: 10人以上, 2: 30人以上 3:50 人以上 4: 100人以上)"
        tenure:
          type: object
          properties:
            started_at:
              type: string
            ended_at:
              type: string
          description: 任期
        content:
          type: string
          description: 經歷內容
      required:
        - position
        - company
        - type
        - title
        - management
        - tenure
        - content
    Education:
      type: object
      description: 教育背景
      properties:
        school:
          type: string
          description: 學校名稱
        status:
          type: integer
          description: 狀態 (0:畢業, 1:肄業, 2:就學中)
        department:
          type: string
          description: 科系
        degree:
          type: integer
          description: 學位 (0:高中職, 1:專科, 2:學士, 3:碩士, 4:博士)
      required:
        - school
        - status
        - department
        - degree
    LangSkill:
      type: object
      properties:
        lang:
          type: string
          description: 語言
        l:
          type: integer
          description: 聽力能力
        s:
          type: integer
          description: 口說能力
        r:
          type: integer
          description: 閱讀能力
        w:
          type: integer
          description: 寫作能力
      required:
        - lang
        - l
        - s
        - r
        - w
    Certificate:
      type: object
      properties:
        code:
          type: integer
          description: 類別代號
        type:
          type: string
          nullable: true
          description: 證書類別
        name:
          type: string
          nullable: true
          description: 證書名稱
      required:
        - code
        - type
        - name
    Company:
      type: object
      properties:
        name:
          type: string
          description: 公司名稱
        avatar:
          type: string
          description: 公司頭像
          nullable: true
        industry:
          type: string
          description: 公司類型
        contact:
          type: string
          description: 公司聯絡人
        phone:
          type: string
          description: 公司聯絡電話
        fax:
          type: string
          description: 公司傳真
          nullable: true
        email:
          type: string
          description: 公司電子信箱
        address:
          type: string
          description: 公司地址
        website:
          type: string
          description: 公司網站
          nullable: true
        contact_time:
          type: string
          description: 公司聯絡時段
          nullable: true
        others:
          type: array
          description: 公司標籤
          nullable: true
          items:
            type: string
        description:
          type: string
          description: 公司簡介
          nullable: true
        remark:
          type: string
          description: 公司備註
          nullable: true
      required:
        - name
        - industry
        - contact
        - phone
        - email
        - address
    Job:
      type: object
      properties:
        status:
          type: integer
          description: "案件狀態（0: 關閉, 1: 開啟）"
        name:
          type: string
          description: 案件名稱
        type:
          type: integer
          description: "案件類型（0：全職, 1：兼職, 2：實習）"
        industry:
          type: array
          description: 產業列表
          items:
            type: integer
        insurance:
          type: boolean
          description: 健保
        demand_amount:
          type: integer
          description: 需求人數
        seniority:
          type: string
          description: 工作年資
        address:
          type: string
          description: 案件所在地址
        working:
          type: object
          description: 工作時間
          properties:
            start_date:
              type: string
              description: 起始日期
            start_time:
              type: string
              description: 結束日期
            end_date:
              type: string
              description: 上班時間
            end_time:
              type: string
              description: 下班時間
        description:
          type: string
          description: 案件內容敘述
        wage:
          type: object
          description: 案件薪酬
          properties:
            type:
              type: integer
              description: "薪酬種類（1：時薪，2：月薪）"
            amount:
              type: string
              description: 薪資
          required:
            - type
            - amount
        tags:
          type: array
          description: 標籤
          items:
            type: string
      required:
        - user_id
        - corp_id
        - status
        - name
        - type
        - industry
        - insurance
        - demand_amount
        - seniority
        - address
        - working
        - description
        - wage
        - tags
    JobDetail:
      type: object
      properties:
        educations:
          type: array
          description: 學歷需求
          items:
            type: object
            properties:
              department:
                type: string
                description: 科系
              degree:
                type: integer
                description: 學位 (0:高中職, 1:專科, 2:學士, 3:碩士, 4:博士)
            required:
              - department
              - degree
        certificates:
          type: array
          description: 證照需求
          items:
            $ref: '#/components/schemas/Certificate'
        lang_skills:
          type: array
          description: 語言需求
          items:
            $ref: '#/components/schemas/LangSkill'
        environments:
          type: object
          description: 環境
          properties:
            name:
              type: string
              description: 環境名稱
            path:
              type: string
              description: 檔案路徑
          required:
            - name
            - path
        skills:
          type: array
          description: 技能需求
          items:
            type: string
        other_demand:
          description: 其他需求
          type: string
      required:
        - educations
        - certificates
        - lang_skills
        - environments
        - skills
        - other_demand
    Recruitment:
      type: object
      properties:
        id:
          type: integer
          description: 招募編號
        job_id:
          type: integer
          description: 對應工作案件編號
        owner_id:
          type: integer
          description: 業主編號
        corp_id:
          type: integer
          description: 企業編號
          nullable: false
        candidate_id:
          type: integer
          description: 招募對象會員編號
        type:
          type: integer
          description: 招募種類（1：招募方徵才，2：求職方應徵）
        status:
          type: integer
          description: 招募狀態（0：一般，1：已婉拒）
        read:
          type: integer
          description: 招募訊息已讀狀態（0：未讀，1：已讀）
        job:
          allOf:
            - type: object
              properties:
                id:
                  type: integer
                  description: 案件編號
              required:
                - id
            - $ref: '#/components/schemas/Job'
      required:
        - id
        - job_id
        - owner_id
        - corp_id
        - candidate_id
        - type
        - status
        - read
        - job
    RecruitmentReqBody:
      type: object
      properties:
        job_id:
          type: integer
          description: 工作案件編號
        candidate_id:
          type: integer
          description: 招募對象user id
      required:
        - job_id
        - candidate_id
    InterviewReqBody:
      type: object
      properties:
        recruitment_id:
          type: integer
          description: 招募編號
        interview_time:
          type: string
          description: 面試時間
        address:
          type: string
          description: 面試地點
        description:
          type: string
          description: 面試說明
      required:
        - recruitment_id
        - interview_time
        - address
        - description
    ChatMessage:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              description: 訊息Id
            user_id:
              type: integer
              description: 發送者Id
            chat_room_id:
              type: integer
              description: 訊息Room Id
          required:
            - id
            - user_id
            - chat_room_id
        - $ref: '#/components/schemas/RequestChatMsg'
    RequestChatMsg:
      type: object
      properties:
        event_type:
          type: integer
          description: 訊息類別(0：聊天訊息，1：案件(任務)，2：應徵職缺，3：邀約職缺，4：面試邀請，5：收取費用，6：系統文字訊息)
        event_id:
          type: integer
          description: 對應物件Id
        message:
          type: string
          description: 訊息內文
          nullable: true
      required:
        - event_type
        - event_id
        - message
    InvalidRequest:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
      required:
        - message
        - errors
    ModelTimestamp:
      type: object
      properties:
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - created_at
        - updated_at

  securitySchemes:
    api_key:
      type: http
      scheme: bearer
      bearerFormat: JWT